# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"


# Time : O(S+T), Space: O(S+T), S=len(s), T=len(t) 
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts = Counter(s)
        countt = Counter(t)

        for i in countt.keys():
            if countt[i] != counts.get(i, 0):
                return i

# Time : O(S+T), Space: O(1)), S=len(s), T=len(t) 
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        so, to = 0, 0

        for c in s:
            so += ord(c)
        
        for c in t:
            to += ord(c)
            
        return  chr(to-so)    